// <auto-generated />
using System;
using MechanicalSheets.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MechanicalSheets.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501080759_AddDescription")]
    partial class AddDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MechanicalSheets.Api.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SheetDefectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetDefectId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.DefectCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DefectCatalogs");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<string>("SheetStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReviewedById");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.SheetDefectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DefectCatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("ExtentHigh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ExtentLow")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ExtentMedium")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("Gravity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("HasPhoto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IntensityHigh")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IntensityLow")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IntensityMedium")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsNa")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsNp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsNr")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsPs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DefectCatalogId");

                    b.HasIndex("SheetId");

                    b.ToTable("SheetDefectItems");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.SheetTechnician", b =>
                {
                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SheetId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SheetTechnicians");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.Attachment", b =>
                {
                    b.HasOne("MechanicalSheets.Api.Models.SheetDefectItem", "SheetDefectItem")
                        .WithMany("Attachments")
                        .HasForeignKey("SheetDefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicalSheets.Api.Models.User", "UploadedBy")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SheetDefectItem");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.Sheet", b =>
                {
                    b.HasOne("MechanicalSheets.Api.Models.User", "CreatedBy")
                        .WithMany("CreatedSheets")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MechanicalSheets.Api.Models.User", "ReviewedBy")
                        .WithMany("ReviewedSheets")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.SheetDefectItem", b =>
                {
                    b.HasOne("MechanicalSheets.Api.Models.DefectCatalog", "DefectCatalog")
                        .WithMany("DefectItems")
                        .HasForeignKey("DefectCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MechanicalSheets.Api.Models.Sheet", "Sheet")
                        .WithMany("DefectItems")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefectCatalog");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.SheetTechnician", b =>
                {
                    b.HasOne("MechanicalSheets.Api.Models.Sheet", "Sheet")
                        .WithMany("Technicians")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicalSheets.Api.Models.User", "User")
                        .WithMany("SheetTechnicians")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sheet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.DefectCatalog", b =>
                {
                    b.Navigation("DefectItems");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.Sheet", b =>
                {
                    b.Navigation("DefectItems");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.SheetDefectItem", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("MechanicalSheets.Api.Models.User", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CreatedSheets");

                    b.Navigation("ReviewedSheets");

                    b.Navigation("SheetTechnicians");
                });
#pragma warning restore 612, 618
        }
    }
}
